intake_platform/intake/curators/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^curators/cp/$", views.CuratorControlPanel.as_view(), name="control_panel"),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/$",
        views.CuratorWPAppsList.as_view(),
        name="apps_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps-hide-slackers/$",
        views.CuratorWPAppsListHideSlackers.as_view(),
        name="apps_list_hide_slackers",
    ),
    url(
        r"^curators/apps-tables/$",
        views.CuratorAppsListTables.as_view(),
        name="apps_list_tables",
    ),
    url(
        r"^curators/app-short-comment/$",
        views.AppCuratorCommentView.as_view(),
        name="app_short_comment",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/accepted/$",
        views.AcceptedAppsList.as_view(),
        name="accepted_apps_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/declined/$",
        views.DeclinedAppsList.as_view(),
        name="declined_apps_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/retry/$",
        views.RetryAppsList.as_view(),
        name="retry_apps_list",
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/$",
        views.CuratorAppDetails.as_view(),
        name="app_details",
    ),
    url(
        r"^curators/apps/accept/$", views.CuratorAcceptApp.as_view(), name="app_accept"
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/decline/$",
        views.CuratorDeclineApp.as_view(),
        name="app_decline",
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/decline-slow/$",
        views.CuratorDeclineAppBecauseSlow.as_view(),
        name="app_decline_because_slow",
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/send-homework/$",
        views.SendHomework.as_view(),
        name="app_send_homework",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/homeworks/(?P<ass_pk>[0-9]+)/$",
        views.InspectHomework.as_view(),
        name="app_inspect_homework",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/homeworks/(?P<ass_pk>[0-9]+)/download$",
        views.DownloadAppHomework.as_view(),
        name="app_download_homework",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/mark-son-of-a-bitch/$",
        views.CuratorAppMarkSonOfABitch.as_view(),
        name="app_mark_son_of_a_bitch",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/DEmark-son-of-a-bitch/$",
        views.CuratorAppDemarkSonOfABitch.as_view(),
        name="app_demark_son_of_a_bitch",
    ),
    url(
        r"^curators/homework/$",
        views.CuratorHomeworkControl.as_view(),
        name="homework_control",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-in-progress/$",
        views.CuratorShoutOut.as_view(),
        name="shout_out",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-accepted/$",
        views.CuratorShoutOutWPAccepted.as_view(),
        name="shout_out_wp_accepted",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-declined/$",
        views.CuratorShoutOutWPDeclined.as_view(),
        name="shout_out_wp_declined",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-slackers/$",
        views.CuratorShoutOutWPSlackers.as_view(),
        name="shout_out_wp_slackers",
    ),
    url(
        r"^curators/email-templates/$",
        views.CuratorEmailTemplatesControl.as_view(),
        name="email_templates_control",
    ),
    url(r"^curators/app-search/$", views.CuratorAppSearch.as_view(), name="app_search"),
    url(r"^curators/stats/$", views.Stats.as_view(), name="stats"),
    url(
        r"^curators/stats/accepted-csv/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.AcceptedAppsCSV.as_view(),
        name="stats-accepted-csv",
    ),
    url(
        r"^curators/stats/accepted-xlsx/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.AcceptedAppsExcel.as_view(),
        name="stats-accepted-xlsx",
    ),
    url(
        r"^curators/stats/passed-csv/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.PassedAppsCSV.as_view(),
        name="stats-passed-csv",
    ),
    url(
        r"^curators/stats/passed-xlsx/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.PassedAppsExcel.as_view(),
        name="stats-passed-xlsx",
    ),
    url(r"^curators/prepods/$", views.CuratorPrepods.as_view(), name="prepods"),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/curators/$",
        views.CuratorCuratorsList.as_view(),
        name="curators_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/curators/add$",
        views.CuratorCuratorAdd.as_view(),
        name="curator_add",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/curators/(?P<curator_pk>[\w-]+)/delete/$",
        views.CuratorCuratorDelete.as_view(),
        name="curator_delete",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/prepods/$",
        views.CuratorPrepodsList.as_view(),
        name="prepods_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/prepods/add/$",
        views.CuratorPrepodAdd.as_view(),
        name="prepod_add",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/prepods/(?P<prepod_pk>[\w-]+)/delete/$",
        views.CuratorPrepodDelete.as_view(),
        name="prepod_delete",
    ),
]

intake_platform/intake/guru/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^guru/check_user/$", views.CheckUser.as_view(), name="check_user"),
    url(r"^guru/revert_user/$", views.RevertUser.as_view(), name="revert_user"),
    url(r"^guru/curators/$", views.CuratorsList.as_view(), name="curators_list"),
    url(r"^guru/curators/add/$", views.AddCurator.as_view(), name="add_curator"),
    url(
        r"^guru/assignments/$",
        views.WPAssignmentsList.as_view(),
        name="assignments_list",
    ),
    url(r"^guru/bucks/$", views.BucksStats.as_view(), name="bucks_stats"),
    url(r"^guru/handymanship/$", views.Handymanship.as_view(), name="handymanship"),
    url(r"^guru/shkololo/$", views.Shkololo.as_view(), name="shkololo"),
    url(r"^guru/spam_list/$", views.SpamList.as_view(), name="spam_list"),
]

# vim: set ts=4 sw=4 sts=4 et :

intake_platform/intake/urls.py
from django.conf.urls import url

from . import staff_views, views

first_step_urls = [
    url(
        r"^tests/lsh101/$",
        views.check_user_not_dumb_prequel,
        name="check_user_not_dumb_prequel",
    ),
    url(
        r"^tests/lsh101/actual-test/$",
        views.check_user_not_dumb_actual_test,
        name="check_user_not_dumb_actual_test",
    ),
    url(r"^single-shot/wp-select/$", views.wp_select, name="program_select"),
    url(r"^single-shot/basic-info/$", views.provide_basic_info, name="provide_basic_info"),
    url(r"^single-shot/contacts/$", views.provide_contacts, name="provide_contacts"),
    url(
        r"^single-shot/education/$",
        views.collect_education_info,
        name="collect_education_info",
    ),
    url(r"^single-shot/activity/$", views.get_activity_info, name="get_activity_info"),
    url(
        r"^single-shot/handyman/$",
        views.demand_handymanship,
        name="demand_handymanship",
    ),
    url(r"^single-shot/money/$", views.fill_in_money, name="fill_in_money"),
    url(r"^single-shot/logistics/$", views.choose_my_way, name="choose_my_way"),
    url(r"^single-shot/promise-help/$", views.promise_help, name="promise_help"),
    url(r"^single-shot/retrospect/$", views.retrospect, name="retrospect"),
    url(r"^single-shot/leak/$", views.leakage, name="leakage"),
    url(r"^single-shot/upload-photo/$", views.upload_photo, name="upload_photo"),
    url(r"^single-shot/parents/$", views.parents, name="parents"),
    url(
        r"^single-shot/complete-first-step/$",
        views.complete_first_step,
        name="complete_first_step",
    ),
    url(r"^timeline/$", views.timeline, name="timeline"),
    url(r"^my-application/$", views.OwnAppReadOnly.as_view(), name="own_app_readonly"),
    url(r"^messages/$", views.Messages.as_view()),
    url(
        r"^emails/show-decline/$",
        views.ReadDeclineEmail.as_view(),
        name="read_decline_email",
    ),
    url(
        r"^homework/do/$",
        views.AssignmentResponse.as_view(),
        name="assignment_response",
    ),
    url(
        r"^homework/download/$",
        views.AssignmentDownload.as_view(),
        name="assignment_download",
    ),
    url(
        r"^homework/my-response-download/$",
        views.AssignmentMyResponseDownload.as_view(),
        name="assignment_my_response_download",
    ),
    #   url(
    #       r"^go-rozetka/$",
    #       views.SecretRozetkaSignUp.as_view(),
    #       name="organizer-rozetka-override",
    #   ),
    #   url(
    #       r"^go-neudobno/$",
    #       views.SecretNeudobnoSignUp.as_view(),
    #       name="organizer-neudobno-override",
    #   ),
    #   url(
    #       r"^go-inclusio/$",
    #       views.SecretInclusioSignUp.as_view(),
    #       name="organizer-inclusio-override",
    #   ),
    #   url(r"^go-field/$", views.SecretFRCSignUp.as_view(), name="frc-override"),
    #   url(r"^go-bypass/$", views.SecretGenericSignUp.as_view(), name="generic-override"),
    url(
        r"^singe-shot/wpc-motivation-edit/$",
        views.WPCMotivationEdit.as_view(),
        name="wpc-motivation-edit",
    ),
]

ajax_urls = [
    url(r"^emails/$", views.emails, name="ajax_emails"),
    url(
        r"^workshop-programs/$", views.workshop_programs, name="ajax_workshop_programs"
    ),
]

staff_urls = [
    url(r"^staff/apps/$", staff_views.AppSearch.as_view(), name="app_search"),
    url(r"^staff/apps/fresh/$", staff_views.FreshAppsView.as_view(), name="fresh_apps"),
    url(
        r"^staff/apps/photo-change-requested/$",
        staff_views.PhotoChangeRequestedAppsView.as_view(),
        name="photo_change_requested_apps",
    ),
    url(r"^staff/twats/$", staff_views.BlackListView.as_view(), name="blacklist"),
    url(
        r"^staff/apps/fresh/(?P<w_slug>[\w-]+)/$",
        staff_views.WorkshopFreshAppsView.as_view(),
        name="workshop_fresh_apps_specific",
    ),
    url(
        r"^staff/apps/suspicious/$",
        staff_views.SuspiciousAppsView.as_view(),
        name="suspicious_apps",
    ),
    url(
        r"^staff/apps/passed/$",
        staff_views.PassedAppsView.as_view(),
        name="passed_apps",
    ),
    url(
        r"^staff/apps/accepted/$",
        staff_views.AllAcceptedApps.as_view(),
        name="workshop_accepted_apps",
    ),
    url(
        r"^staff/apps/accepted/(?P<w_slug>[\w-]+)/$",
        staff_views.WorkshopAcceptedApps.as_view(),
        name="workshop_accepted_apps_specific",
    ),
    url(
        r"^staff/apps/accepted/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        staff_views.WorkshopProgramAcceptedApps.as_view(),
        name="workshop_program_accepted_apps",
    ),
    url(
        r"^staff/apps/rejected/$",
        staff_views.RejectedAppsView.as_view(),
        name="rejected_apps",
    ),
    url(
        r"^staff/apps/suspicious/$",
        staff_views.SuspiciousAppsView.as_view(),
        name="suspicious_apps",
    ),
    url(
        r"^staff/apps/workshop-declined/$",
        staff_views.WorkshopDeclinedApps.as_view(),
        name="workshop_declined_apps",
    ),
    url(
        r"^staff/apps/workshop-declined/(?P<w_slug>[\w-]+)/$",
        staff_views.WorkshopDeclinedAppsSpecific.as_view(),
        name="workshop_declined_apps_specific",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/$",
        staff_views.AppDetailView.as_view(),
        name="app_detail",
    ),
    # actions
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/mark-suspicious/$",
        staff_views.mark_suspicious,
        name="mark_suspicious",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/demark-suspicious/$",
        staff_views.demark_suspicious,
        name="demark_suspicious",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/accept/$",
        staff_views.accept_app,
        name="accept_app",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/reject-a-reno/$",
        staff_views.RejectAppFromNabor.as_view(),
        name="reject_app",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/unreject/$",
        staff_views.unreject_app,
        name="unreject_app",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/case-reopen/$",
        staff_views.reopen_app_case,
        name="reopen_app_case",
    ),
    url(r"^staff/apps/return-app/$", staff_views.return_app, name="return_app"),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/comment/$",
        staff_views.AppCommentView.as_view(),
        name="comment_app",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/request-photo-change/$",
        staff_views.RequestPhotoChange.as_view(),
        name="request_photo_change",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/change-workshop/$",
        staff_views.ChangeAppWorkshop.as_view(),
        name="change_app_workshop",
    ),
    url(
        r"^staff/ask-nicely/replace-photo/$",
        views.ReplacePhoto.as_view(),
        name="replace_photo",
    ),
]

urlpatterns = first_step_urls + ajax_urls + staff_urls

intake_platform/intake_platform/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from intake_platform.common import views as common_views

from .views import IndexView, TestView, logout

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^$", IndexView.as_view(), name="index"),
    url(r'logout', logout),
    url(r"^test/$", TestView.as_view(), name="test"),
    # third-party stuff
    url(r"^selectable/", include("selectable.urls")),
    url(r"^accounts/profile/$", common_views.profile, name="profile"),
    url(r"^help/$", common_views.help, name="help"),
    # intake
    url("", include(("intake_platform.intake.urls", "intake"), namespace="intake")),
    # curators
    url(
        "",
        include(
            ("intake_platform.intake.curators.urls", "curators"), namespace="curators"
        ),
    ),
    # guru
    url("", include(("intake_platform.intake.guru.urls", "guru"), namespace="guru")),
    url('', include('django.contrib.auth.urls')),
    url('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intake_platform/intake/guru/forms.py
# coding: utf-8

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, HTML  # Div, Hidden
from crispy_forms.bootstrap import FormActions

from ..models import WorkshopProgramMetaInfo
from ..widgets import CheckboxSelectMultiple


class WPSelectMultipleForm(forms.Form):
    programs = forms.ModelMultipleChoiceField(
        queryset=WorkshopProgramMetaInfo.objects.all(), widget=CheckboxSelectMultiple
    )
    user_pk = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super(WPSelectMultipleForm, self).__init__(*args, **kwargs)

        helper = FormHelper(self)
        helper.layout = Layout(
            Field("programs"),
            Field("user_pk"),
            FormActions(
                Submit(
                    "submit",
                    u"Сделать куратором выбранных направлений",
                    css_class="btn btn-primary",
                ),
                HTML(
                    u"""
                     {% for url, caption in back_urls %}
                     <a class="btn btn-default" href="{{ url }}">{{ caption }}</a>
                     {% endfor %}
                     """
                ),
            ),
        )
        self.helper = helper

intake_platform/intake/templates/intake/curators/_apps_list_accept_modal.html
<div class="modal fade" id="modal_acceptapp" tabindex="-1" role="dialog" aria-labelledby="modal_acceptapp_label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal_acceptapp_label">Подтверждение</h4>
      </div>
      <div class="modal-body">
        <form method="POST" action='{% url "curators:app_accept" %}' id="form_accept_app">
          {% csrf_token %}
          <div class="form-group">
            <input type="hidden" id="a_pk" name="a_pk">
            <input type="hidden" id="back_url" name="back_url">
          </div>
          <div class="form-group">

            <p><b>Анкета:</b> <span id="recipient-name"></span><br/>
            <B>Мастерская:</b> <span id="a_workshop"></span><br/>
            <b>Программа:</b> <span id="a_program"></span></p>

            <p>Берём эту анкету?</p>
            
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
        <button type="button" class="btn btn-primary" id="submit_btn">Вперёд</button>
      </div>
    </div>
  </div>
</div>

intake_platform/intake/templates/intake/curators/accepted_apps_list.html
{% extends "base.html" %}


{% block jumbotron_content %}
  <h1>{{workshop_name|title}}<small>/{{program_name}}</small></h1>
  <h2>Принятые заявки</h2>

<ul class="nav nav-pills" role="tablist">
  <li role="presentation">{% include 'intake/curators/_wp_apps_tab.html' %}</li>
  <li role="presentation">{% include 'intake/curators/_wp_retry_tab.html' %}</li>
  <li role="presentation" class="active">{% include 'intake/curators/_wp_accepted_tab.html' %}</li>
  <li role="presentation">{% include 'intake/curators/_wp_declined_tab.html' %}</li>
</ul>

{% include 'intake/curators/_prepods_inactive_tabs.html' %}

<p><a href="{% url 'curators:shout_out_wp_accepted' workshop_slug program_slug %}" class="btn btn-default">Шатаут этим принятым</a></p>

{% endblock %}

{% block content %}
<div class="container">
{% for a in applications %}
  {% with a.full_info as u %}

<div class="row thumbnail" id="applicant-{{a.pk}}">
  {% if a.bucks.son_of_a_bitch %}
    <div class="col-md-8">
    недоехавший участник:
    {{ u.last_name }} {{ u.first_name }} <span class="text-muted">{{ u.middle_name }}</span>
    <a href="mailto:{{ u.email }}">{{ u.email }}</a>
    </div>
    <div class="col-md-2"><a href="{% url 'curators:app_demark_son_of_a_bitch' a.pk %}">Снять метку</a></div>
  {% else %}
  <div class="col-md-2">
    <div class="thumbnail">
      <img src="{{ u.photo.photo_absolute_url }}">
    </div>

    {% if a.is_changeable_by_curator %}
      <div class="caption">
        <p><a href="{% url 'curators:app_accept' a.pk %}" class="btn btn-primary" role="button"> Принять </a></p>
        <p>
          <a href="{% url 'curators:app_decline' a.pk %}" class="btn btn-default" role="button">
             Отказать
          </a>
        </p>
      </div>
    {% endif %}
  </div>

  <div class="col-md-5">
    <h4>{{ u.last_name }} {{ u.first_name }} <span class="text-muted">{{ u.middle_name }}</span></h4>
    <dt><small>{{ u.location }}</small></dt>
    <dd><small>Возраст: {{ u.age }} (ДР {{ u.birthdate }})</small></dd>

    <dl>
      <dt>email: <a href="mailto:{{ u.email }}">{{ u.email }}</a></dt>
      {% if u.uac %}
        <dt>Другие контакты:</dt>
        {% for c_label, c in u.uac.get_data %}
          <dd><strong>{{ c_label}}:</strong> {{ c }}</dd>
        {% empty %}
          <dd>Других контактов не указано</dd>
        {% endfor %}
      {% endif %}

      {% if u.is_underage %}
        <dt>Родитель </dt>
        {% if u.underage_data.parental_confirm %}<dd>(согласие получено)</dd>{% endif %}
        <dd>{{ u.underage_data.parental_phone }}</dd>
        <dd>{{ u.underage_data.parental_name }}</dd>
      {% endif %}
    </dl>

    <a href="{% url 'curators:app_details' a.pk %}">Вся анкета</a>

  </div>

  <div class="col-md-5">
      <dt>Заявка создана</dt>
        <dd>{{ a.created }}<br/>
        {{ a.created|timesince }} назад</dd>
      <dt>Прошла 1-й тур</dt>
        <dd>{{ a.bucks.passed_first_step }}<br/>
        {{ a.bucks.passed_first_step|timesince }} назад</dd>
      <dt>Взята нами</dt>
      <dd>{{ a.bucks.accepted_by_workshop }}<br/>
        {{ a.bucks.accepted_by_workshop|timesince }} назад</dd>

      {% if a.has_homework %}
        {% if a.has_complete_homework %}
          <dt>Есть ответ на вступительно {{ a.get_homework.date_uploaded }}</dt>
          <dd><a class="btn btn-default" href="{% url 'curators:app_inspect_homework' a.pk a.get_homework.pk %}">Посмотреть</a> <a class="btn btn-info" href="{{ a.get_homework.response_absolute_url }}">Скачать файл ответа</a></dd>
        {% else %}
          <dd><em>Участник получил вступительное задание {{ a.homework_sent_datetime|timesince }} назад</em></dd>
          <dd><abbr title="Когда ответ будет получен, здесь будет кнопка, нажав на которую можно будет скачать ответ на задание, которое было отправлено этому участнику.">(Ответа ещё не получили)</abbr></dd>
        {% endif %}
      {% else %}
        {% if wp_has_assignment %}
          <dt>Выполненного задания нет</dt>
          <dd><a href="{% url 'curators:app_send_homework' a.pk %}" class="btn btn-default">Выслать</a></dd>
        {% endif %}
      {% endif %}

      <br/>
      <a class="btn btn-warning" href="#" id="mark-son-of-a-bitch-button-for-{{ a.pk }}">Участник не приехал</a>
      <div class="hidden" id="son-of-a-bitch-form-for-{{a.pk}}">
        <form method="POST" action="{% url 'curators:app_mark_son_of_a_bitch' a.pk %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-default">Подтверждаю</button>
        </form>
      </div>
  </div>

  {% endif %}
</div> <!-- /row for application {{ a.pk }} //-->

  {% endwith %}
{% empty %}
<div class="row">
  <div class="col-md-6">
Нет заявок.
  </div>
</div>
{% endfor %}


{% include "intake/_paginator.html" %}

{% block extra_scripts %}
<script>
{% for a in applications %}
  $("#mark-son-of-a-bitch-button-for-{{a.pk}}").unbind('click').bind('click', function() {

    var f = $("#son-of-a-bitch-form-for-{{a.pk}}");
    if (f.hasClass('hidden')) {
      f.removeClass('hidden').addClass('visible');
    } else {
      f.removeClass('visible').addClass('hidden');
    }

    return false;
  });
{% endfor %}
</script>
{% endblock extra_scripts %}

</div>
{% endblock %}

intake_platform/intake/templates/intake/curators/apps_list.html
{% extends "base.html" %}


{% block jumbotron_content %}
  <h2>{{workshop_name|title}}<small>/{{program_name}}</small></h2>
  {#<p>Из новенького: появились шатауты на разные классы, не только на впроцессников.</p>#}
  {#<p>В ближайшем будущем: <s>шатауты подмножеству анкет</s>, связь с участником с сайта, массовые операции.</p>#}
{#  <p>Перед началом работы прочитайте наш <a href="https://docs.google.com/document/d/1WQFL7w26umqXcfhVgqXP6SSSFYN1gDHPvMacQdcp3yE/edit">мануал куратора</a> с картинками</p>#}
  <h2>Заявки</h2>
<ul class="nav nav-pills" role="tablist">
  <li role="presentation" class="active">{% include 'intake/curators/_wp_apps_tab.html' %}</li>
  <li role="presentation">{% include 'intake/curators/_wp_retry_tab.html' %}</li>
  <li role="presentation">{% include 'intake/curators/_wp_accepted_tab.html' %}</li>
  <li role="presentation">{% include 'intake/curators/_wp_declined_tab.html' %}</li>
</ul>

{% include 'intake/curators/_prepods_inactive_tabs.html' %}

<hr>
  <p><a href="{% url 'curators:shout_out' workshop_slug program_slug %}" class="btn btn-default">Сделать Шатаут всем  впроцессникам</a> &mdash; это те, кто в этой вкладке, без разницы, прислали они вступительное или нет.</p>
  <p><a href="{% url 'curators:shout_out_wp_slackers' workshop_slug program_slug %}" class="btn btn-default">Сделать Шатаут всем <b>тормозам</b></a> &mdash; такой шатаут получат только те, кто не прислал вступительное</p>

  <p>Алсо, те кто ещё не получал вступительное могут его получить если вы нажмёте на волшебную кнопку рядом с анкетой.</p>

  {% block slackers_toggle %}

  <p><a href="{% url 'curators:apps_list_hide_slackers' workshop_slug program_slug %}" class="btn btn-default">Скрыть тех, кто не прислал ответ на задание</a></p>
  {% endblock slackers_toggle %}

{% endblock %}

{% block content %}
  {% include "intake/curators/_apps_list_accept_modal.html" %}
  {% include 'intake/curators/_apps_list_paginated.html' %}
{% endblock %}

{% block extra_scripts %}
  {% include "intake/curators/_apps_list_accept_modal.js" %}
{% endblock extra_scripts %}