intake_platform/intake/curators/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^curators/cp/$", views.CuratorControlPanel.as_view(), name="control_panel"),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/$",
        views.CuratorWPAppsList.as_view(),
        name="apps_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps-hide-slackers/$",
        views.CuratorWPAppsListHideSlackers.as_view(),
        name="apps_list_hide_slackers",
    ),
    url(
        r"^curators/apps-tables/$",
        views.CuratorAppsListTables.as_view(),
        name="apps_list_tables",
    ),
    url(
        r"^curators/app-short-comment/$",
        views.AppCuratorCommentView.as_view(),
        name="app_short_comment",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/accepted/$",
        views.AcceptedAppsList.as_view(),
        name="accepted_apps_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/declined/$",
        views.DeclinedAppsList.as_view(),
        name="declined_apps_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/apps/retry/$",
        views.RetryAppsList.as_view(),
        name="retry_apps_list",
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/$",
        views.CuratorAppDetails.as_view(),
        name="app_details",
    ),
    url(
        r"^curators/apps/accept/$", views.CuratorAcceptApp.as_view(), name="app_accept"
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/decline/$",
        views.CuratorDeclineApp.as_view(),
        name="app_decline",
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/decline-slow/$",
        views.CuratorDeclineAppBecauseSlow.as_view(),
        name="app_decline_because_slow",
    ),
    url(
        r"^curators/apps/(?P<pk>[0-9]+)/send-homework/$",
        views.SendHomework.as_view(),
        name="app_send_homework",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/homeworks/(?P<ass_pk>[0-9]+)/$",
        views.InspectHomework.as_view(),
        name="app_inspect_homework",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/homeworks/(?P<ass_pk>[0-9]+)/download$",
        views.DownloadAppHomework.as_view(),
        name="app_download_homework",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/mark-son-of-a-bitch/$",
        views.CuratorAppMarkSonOfABitch.as_view(),
        name="app_mark_son_of_a_bitch",
    ),
    url(
        r"^curators/apps/(?P<app_pk>[0-9]+)/DEmark-son-of-a-bitch/$",
        views.CuratorAppDemarkSonOfABitch.as_view(),
        name="app_demark_son_of_a_bitch",
    ),
    url(
        r"^curators/homework/$",
        views.CuratorHomeworkControl.as_view(),
        name="homework_control",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-in-progress/$",
        views.CuratorShoutOut.as_view(),
        name="shout_out",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-accepted/$",
        views.CuratorShoutOutWPAccepted.as_view(),
        name="shout_out_wp_accepted",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-declined/$",
        views.CuratorShoutOutWPDeclined.as_view(),
        name="shout_out_wp_declined",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/shout-slackers/$",
        views.CuratorShoutOutWPSlackers.as_view(),
        name="shout_out_wp_slackers",
    ),
    url(
        r"^curators/email-templates/$",
        views.CuratorEmailTemplatesControl.as_view(),
        name="email_templates_control",
    ),
    url(r"^curators/app-search/$", views.CuratorAppSearch.as_view(), name="app_search"),
    url(r"^curators/stats/$", views.Stats.as_view(), name="stats"),
    url(
        r"^curators/stats/accepted-csv/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.AcceptedAppsCSV.as_view(),
        name="stats-accepted-csv",
    ),
    url(
        r"^curators/stats/accepted-xlsx/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.AcceptedAppsExcel.as_view(),
        name="stats-accepted-xlsx",
    ),
    url(
        r"^curators/stats/passed-csv/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.PassedAppsCSV.as_view(),
        name="stats-passed-csv",
    ),
    url(
        r"^curators/stats/passed-xlsx/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        views.PassedAppsExcel.as_view(),
        name="stats-passed-xlsx",
    ),
    url(r"^curators/prepods/$", views.CuratorPrepods.as_view(), name="prepods"),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/curators/$",
        views.CuratorCuratorsList.as_view(),
        name="curators_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/curators/add$",
        views.CuratorCuratorAdd.as_view(),
        name="curator_add",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/curators/(?P<curator_pk>[\w-]+)/delete/$",
        views.CuratorCuratorDelete.as_view(),
        name="curator_delete",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/prepods/$",
        views.CuratorPrepodsList.as_view(),
        name="prepods_list",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/prepods/add/$",
        views.CuratorPrepodAdd.as_view(),
        name="prepod_add",
    ),
    url(
        r"^curators/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/elders/prepods/(?P<prepod_pk>[\w-]+)/delete/$",
        views.CuratorPrepodDelete.as_view(),
        name="prepod_delete",
    ),
]

intake_platform/intake/guru/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^guru/check_user/$", views.CheckUser.as_view(), name="check_user"),
    url(r"^guru/revert_user/$", views.RevertUser.as_view(), name="revert_user"),
    url(r"^guru/curators/$", views.CuratorsList.as_view(), name="curators_list"),
    url(r"^guru/curators/add/$", views.AddCurator.as_view(), name="add_curator"),
    url(
        r"^guru/assignments/$",
        views.WPAssignmentsList.as_view(),
        name="assignments_list",
    ),
    url(r"^guru/bucks/$", views.BucksStats.as_view(), name="bucks_stats"),
    url(r"^guru/handymanship/$", views.Handymanship.as_view(), name="handymanship"),
    url(r"^guru/shkololo/$", views.Shkololo.as_view(), name="shkololo"),
    url(r"^guru/spam_list/$", views.SpamList.as_view(), name="spam_list"),
]

# vim: set ts=4 sw=4 sts=4 et :

intake_platform/intake/urls.py
from django.conf.urls import url

from . import staff_views, views

first_step_urls = [
    url(
        r"^tests/lsh101/$",
        views.check_user_not_dumb_prequel,
        name="check_user_not_dumb_prequel",
    ),
    url(
        r"^tests/lsh101/actual-test/$",
        views.check_user_not_dumb_actual_test,
        name="check_user_not_dumb_actual_test",
    ),
    url(r"^single-shot/wp-select/$", views.wp_select, name="program_select"),
    url(r"^single-shot/basic-info/$", views.provide_basic_info, name="provide_basic_info"),
    url(r"^single-shot/contacts/$", views.provide_contacts, name="provide_contacts"),
    url(
        r"^single-shot/education/$",
        views.collect_education_info,
        name="collect_education_info",
    ),
    url(r"^single-shot/activity/$", views.get_activity_info, name="get_activity_info"),
    url(
        r"^single-shot/handyman/$",
        views.demand_handymanship,
        name="demand_handymanship",
    ),
    url(r"^single-shot/money/$", views.fill_in_money, name="fill_in_money"),
    url(r"^single-shot/logistics/$", views.choose_my_way, name="choose_my_way"),
    url(r"^single-shot/promise-help/$", views.promise_help, name="promise_help"),
    url(r"^single-shot/retrospect/$", views.retrospect, name="retrospect"),
    url(r"^single-shot/leak/$", views.leakage, name="leakage"),
    url(r"^single-shot/upload-photo/$", views.upload_photo, name="upload_photo"),
    url(r"^single-shot/parents/$", views.parents, name="parents"),
    url(
        r"^single-shot/complete-first-step/$",
        views.complete_first_step,
        name="complete_first_step",
    ),
    url(r"^timeline/$", views.timeline, name="timeline"),
    url(r"^my-application/$", views.OwnAppReadOnly.as_view(), name="own_app_readonly"),
    url(r"^messages/$", views.Messages.as_view()),
    url(
        r"^emails/show-decline/$",
        views.ReadDeclineEmail.as_view(),
        name="read_decline_email",
    ),
    url(
        r"^homework/do/$",
        views.AssignmentResponse.as_view(),
        name="assignment_response",
    ),
    url(
        r"^homework/download/$",
        views.AssignmentDownload.as_view(),
        name="assignment_download",
    ),
    url(
        r"^homework/my-response-download/$",
        views.AssignmentMyResponseDownload.as_view(),
        name="assignment_my_response_download",
    ),
    #   url(
    #       r"^go-rozetka/$",
    #       views.SecretRozetkaSignUp.as_view(),
    #       name="organizer-rozetka-override",
    #   ),
    #   url(
    #       r"^go-neudobno/$",
    #       views.SecretNeudobnoSignUp.as_view(),
    #       name="organizer-neudobno-override",
    #   ),
    #   url(
    #       r"^go-inclusio/$",
    #       views.SecretInclusioSignUp.as_view(),
    #       name="organizer-inclusio-override",
    #   ),
    #   url(r"^go-field/$", views.SecretFRCSignUp.as_view(), name="frc-override"),
    #   url(r"^go-bypass/$", views.SecretGenericSignUp.as_view(), name="generic-override"),
    url(
        r"^singe-shot/wpc-motivation-edit/$",
        views.WPCMotivationEdit.as_view(),
        name="wpc-motivation-edit",
    ),
]

ajax_urls = [
    url(r"^emails/$", views.emails, name="ajax_emails"),
    url(
        r"^workshop-programs/$", views.workshop_programs, name="ajax_workshop_programs"
    ),
]

staff_urls = [
    url(r"^staff/apps/$", staff_views.AppSearch.as_view(), name="app_search"),
    url(r"^staff/apps/fresh/$", staff_views.FreshAppsView.as_view(), name="fresh_apps"),
    url(
        r"^staff/apps/photo-change-requested/$",
        staff_views.PhotoChangeRequestedAppsView.as_view(),
        name="photo_change_requested_apps",
    ),
    url(r"^staff/twats/$", staff_views.BlackListView.as_view(), name="blacklist"),
    url(
        r"^staff/apps/fresh/(?P<w_slug>[\w-]+)/$",
        staff_views.WorkshopFreshAppsView.as_view(),
        name="workshop_fresh_apps_specific",
    ),
    url(
        r"^staff/apps/suspicious/$",
        staff_views.SuspiciousAppsView.as_view(),
        name="suspicious_apps",
    ),
    url(
        r"^staff/apps/passed/$",
        staff_views.PassedAppsView.as_view(),
        name="passed_apps",
    ),
    url(
        r"^staff/apps/accepted/$",
        staff_views.AllAcceptedApps.as_view(),
        name="workshop_accepted_apps",
    ),
    url(
        r"^staff/apps/accepted/(?P<w_slug>[\w-]+)/$",
        staff_views.WorkshopAcceptedApps.as_view(),
        name="workshop_accepted_apps_specific",
    ),
    url(
        r"^staff/apps/accepted/(?P<w_slug>[\w-]+)/(?P<p_slug>[\w-]+)/$",
        staff_views.WorkshopProgramAcceptedApps.as_view(),
        name="workshop_program_accepted_apps",
    ),
    url(
        r"^staff/apps/rejected/$",
        staff_views.RejectedAppsView.as_view(),
        name="rejected_apps",
    ),
    url(
        r"^staff/apps/suspicious/$",
        staff_views.SuspiciousAppsView.as_view(),
        name="suspicious_apps",
    ),
    url(
        r"^staff/apps/workshop-declined/$",
        staff_views.WorkshopDeclinedApps.as_view(),
        name="workshop_declined_apps",
    ),
    url(
        r"^staff/apps/workshop-declined/(?P<w_slug>[\w-]+)/$",
        staff_views.WorkshopDeclinedAppsSpecific.as_view(),
        name="workshop_declined_apps_specific",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/$",
        staff_views.AppDetailView.as_view(),
        name="app_detail",
    ),
    # actions
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/mark-suspicious/$",
        staff_views.mark_suspicious,
        name="mark_suspicious",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/demark-suspicious/$",
        staff_views.demark_suspicious,
        name="demark_suspicious",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/accept/$",
        staff_views.accept_app,
        name="accept_app",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/reject-a-reno/$",
        staff_views.RejectAppFromNabor.as_view(),
        name="reject_app",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/unreject/$",
        staff_views.unreject_app,
        name="unreject_app",
    ),
    url(
        r"^staff/apps/(?P<app_pk>[0-9]+)/case-reopen/$",
        staff_views.reopen_app_case,
        name="reopen_app_case",
    ),
    url(r"^staff/apps/return-app/$", staff_views.return_app, name="return_app"),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/comment/$",
        staff_views.AppCommentView.as_view(),
        name="comment_app",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/request-photo-change/$",
        staff_views.RequestPhotoChange.as_view(),
        name="request_photo_change",
    ),
    url(
        r"^staff/apps/(?P<pk>[0-9]+)/change-workshop/$",
        staff_views.ChangeAppWorkshop.as_view(),
        name="change_app_workshop",
    ),
    url(
        r"^staff/ask-nicely/replace-photo/$",
        views.ReplacePhoto.as_view(),
        name="replace_photo",
    ),
]

urlpatterns = first_step_urls + ajax_urls + staff_urls

intake_platform/intake_platform/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from intake_platform.common import views as common_views

from .views import IndexView, TestView, logout

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^$", IndexView.as_view(), name="index"),
    url(r'logout', logout),
    url(r"^test/$", TestView.as_view(), name="test"),
    # third-party stuff
    url(r"^selectable/", include("selectable.urls")),
    url(r"^accounts/profile/$", common_views.profile, name="profile"),
    url(r"^help/$", common_views.help, name="help"),
    # intake
    url("", include(("intake_platform.intake.urls", "intake"), namespace="intake")),
    # curators
    url(
        "",
        include(
            ("intake_platform.intake.curators.urls", "curators"), namespace="curators"
        ),
    ),
    # guru
    url("", include(("intake_platform.intake.guru.urls", "guru"), namespace="guru")),
    url('', include('django.contrib.auth.urls')),
    url('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intake_platform/intake/guru/forms.py
# coding: utf-8

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, HTML  # Div, Hidden
from crispy_forms.bootstrap import FormActions

from ..models import WorkshopProgramMetaInfo
from ..widgets import CheckboxSelectMultiple


class WPSelectMultipleForm(forms.Form):
    programs = forms.ModelMultipleChoiceField(
        queryset=WorkshopProgramMetaInfo.objects.all(), widget=CheckboxSelectMultiple
    )
    user_pk = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super(WPSelectMultipleForm, self).__init__(*args, **kwargs)

        helper = FormHelper(self)
        helper.layout = Layout(
            Field("programs"),
            Field("user_pk"),
            FormActions(
                Submit(
                    "submit",
                    u"Сделать куратором выбранных направлений",
                    css_class="btn btn-primary",
                ),
                HTML(
                    u"""
                     {% for url, caption in back_urls %}
                     <a class="btn btn-default" href="{{ url }}">{{ caption }}</a>
                     {% endfor %}
                     """
                ),
            ),
        )
        self.helper = helper

intake_platform/intake/templates/intake/curators/elders/_add_elder_dropdown.html
<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Добавить <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="{% url 'curators:curator_add' workshop_slug program_slug  %}">Добавить куратора</a></li>
    <li><a href="{% url 'curators:prepod_add' workshop_slug program_slug  %}">Добавить препода</a></li>
    <li class="disabled"><a href="#">Добавить &laquo;Золотого лектора&raquo&raquo;</a></li>
  </ul>
</div>

intake_platform/intake/templates/intake/curators/elders/curators_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_title %} Преподы {{ workshop_slug }}/{{ program_slug }}{% endblock %}

{% block jumbotron_content %}
  <h2>{{workshop_name|title}}<small>/{{program_name}}</small></h2>

  {% include 'intake/curators/_apps_inactive_tabs.html' %}

<h2>Старший состав</h2>
<ul class="nav nav-pills" role="tablist">
  <li role="presentation" class="active">{% include 'intake/curators/_wp_curators_tab.html' %}</li>
  <li role="presentation">{% include 'intake/curators/_wp_prepods_tab.html' %}</li>
  <li role="presentation" class="disabled">{% include 'intake/curators/_wp_vip_tab.html' %}</li>
{% include 'intake/curators/elders/_add_elder_dropdown.html' %}
</ul>


{% endblock %}

{% block content %}
<div class="container">
  <h2>Закреплённые за направлением кураторы</h2>
  <h4>{{ workshop_name }}:{{ program_name }}</h4>
  <p>Кнопка "исправить" пока не работает, если надо что-то поменять, придётся удалить и потом создать нового.</p>
{% for curator in curators %}
  {% with curator.full_info as info %}

  <!-- Deletion modal -->
  <div class="modal" id="myDeleteModal{{ curator.pk }}" tabindex="-1" role="dialog" aria-labelledby="myDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
    <form action="{% url "curators:curator_delete" workshop_slug program_slug curator.pk %}" method="post">{% csrf_token %}
        <div class="modal-body">
            <p>Информация про куратора "{{ curator }}" будет удалена. Это то, что мы хотим?</p>
        </div><!-- /modal-body -->

        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Да, удалить</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть это окно</button>
        </div>
  </form>
      </div> <!-- /modal-content -->
    </div>
  </div>

  {% if forloop.first %}<div class="row">
  {% elif forloop.counter0|divisibleby:"2" %}</div><div class="row">{% endif %}
    <div class="col-md-3">
      <div class="thumbnail">
      {% if info.photo %}
        <img class="img-responsive img-rounded" src="{{ info.photo.photo_absolute_url }}">
      {% else %}
        <img class="img-responsive img-rounded" src="{% static 'img/default-user-image.png' %}">
      {% endif %}

        <div class="caption">
          <h4>{{ info.last_name }} {{ info.first_name }}</h4>
          <h4 class="text-muted">{{ info.middle_name }}
          {% if info.is_tent_friendly %}
            <small class="glyphicon glyphicon-tent"></small>
          {% endif %}</h4>
          <dl>
            <dt><a href="mailto:{{ info.email }}">{{ info.email }}</a></dt>
            {% for c_label, c_val in info.contacts_data %}
              <dd><strong>{{ c_label}}:</strong> {{ c_val }}</dd>
            {% endfor %}
          </dl>

            <a href="#" role="button" class="btn btn-default disabled">
              Исправить
            </a>

            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myDeleteModal{{ curator.pk }}">
              Удалить
            </button>

        </div>
      </div><!-- /thumbnail -->
    </div><!-- /col-md-3 -->

    <div class="col-md-3">
      <dl>
        <dt>На ЛШ</dt>
        <dd>Приезжает {{ info.arrival_date|date:"d E Y" }}</dd>
        <dd>Уезжает {{ info.departure_date|date:"d E Y" }}</dd>
        <dd><strong>Жильё</strong>: {{ info.housing }}</dd>
      </dl>
      <hr/>
      <h4>Комментарий</h4>
      <p>{{ info.comment }}</p>
    </div>
  {% endwith %}
    {% if forloop.last %}</div>{% endif %}
{% endfor %}

{% include "intake/_paginator.html" %}

</div>
{% endblock %}

intake_platform/intake/templates/intake/curators/elders/prepods_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_title %} Преподы {{ workshop_slug }}/{{ program_slug }}{% endblock %}

{% block jumbotron_content %}
  <h2>{{workshop_name|title}}<small>/{{program_name}}</small></h2>

  {% include 'intake/curators/_apps_inactive_tabs.html' %}

<h2>Старший состав</h2>
<ul class="nav nav-pills" role="tablist">
  <li role="presentation" class="disabled">{% include 'intake/curators/_wp_curators_tab.html' %}</li>
  <li role="presentation" class="active">{% include 'intake/curators/_wp_prepods_tab.html' %}</li>
  <li role="presentation" class="disabled">{% include 'intake/curators/_wp_vip_tab.html' %}</li>
{% include 'intake/curators/elders/_add_elder_dropdown.html' %}
</ul>


{% endblock %}

{% block content %}
<div class="container">
  <h2>Закреплённые за направлением преподы</h2>
  <h4>{{ workshop_name }}:{{ program_name }}</h4>
  <p>Кнопа "исправить" пока не работает, если надо что-то поменять, придётся удалить препода и потом создать нового.</p>
{% for prep in prepods %}
  {% with prep.full_info as info %}

  <!-- Deletion modal -->
  <div class="modal" id="myDeleteModal{{ prep.pk }}" tabindex="-1" role="dialog" aria-labelledby="myDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
  <form action="{% url "curators:prepod_delete" workshop_slug program_slug prep.pk %}" method="post">{% csrf_token %}
        <div class="modal-body">
            <p>Информация про преподавателя "{{ prep }}" будет удалена. Это то, что мы хотим?</p>
        </div><!-- /modal-body -->

        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Да, удалить</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть это окно</button>
        </div>
  </form>
      </div> <!-- /modal-content -->
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="thumbnail">
      {% if info.photo %}
        <img class="img-responsive img-rounded" src="{{ info.photo.photo_absolute_url }}">
      {% else %}
        <img class="img-responsive img-rounded" src="{% static 'img/default-user-image.png' %}">
      {% endif %}

        <div class="caption">
          <h4>{{ info.last_name }} {{ info.first_name }}</h4>
          <h4 class="text-muted">{{ info.middle_name }}
          {% if info.is_tent_friendly %}
            <small class="glyphicon glyphicon-tent"></small>
          {% endif %}</h4>
          <dl>
            <dt><a href="mailto:{{ info.email }}">{{ info.email }}</a></dt>
            {% for c_label, c_val in info.contacts_data %}
              <dd><strong>{{ c_label}}:</strong> {{ c_val }}</dd>
            {% endfor %}
          </dl>

            <a href="#" role="button" class="btn btn-default disabled">
              Исправить
            </a>

            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myDeleteModal{{ prep.pk }}">
              Удалить
            </button>

        </div>
      </div><!-- /thumbnail -->
    </div><!-- /col-md-3 -->

    <div class="col-md-9">
      <div class="row">
        <div class="col-md-6">
          <dl>
            <dt>На ЛШ</dt>
              <dd>Приезжает {{ info.arrival_date|date:"d E Y" }}</dd>
              <dd>Уезжает {{ info.departure_date|date:"d E Y" }}</dd>
              <dd><strong>Жильё</strong>: {{ info.housing }}</dd>
          </dl>
          {% for lecture in info.lectures %}
            {% if forloop.first %}
              <h4>Лекции/семинары</h4>
                <ul class="list-unstyled">
            {% endif %}
                  <li>
                    <strong>[{{ lecture.date|date:"d E" }}]</strong>
                    &laquo;{{ lecture.title }}&raquo;
                  </li>
            {% if forloop.last %}
                </ul>
            {% endif %}
          {% endfor %}
        </div>
        <div class="col-md-6">
          <small>
            <dl>
              <dt>Образование</dt>
                <dd>{{ info.education }}</dd>
              <dt>Место работы</dt>
                <dd>{{ info.affiliation }}</dd>
              <dt>Академический статус</dt>
                <dd>{{ info.academic_status }}</dd>
            </dl>
          </small>
        </div>
      </div><!-- /row  -->
      <hr/>
      <div class="row">
        <div class="col-md-6">
          <h4>Общие темы вещания</h4>
          <p>{{ info.topic }}</p>
        </div>
        <div class="col-md-6">
          <h4>Комментарий</h4>
          <p>{{ info.comment }}</p>
        </div>
      </div>
    </div>
  {% endwith %}
</div><!-- row -->
{% endfor %}

{% include "intake/_paginator.html" %}

</div>
{% endblock %}